eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8210
spring:
  application:
    name: service-workflow
  cloud:
    config:
      label: master
      uri: http://localhost:8300/
      profile: dev